---
- name: Converge with one declared key
  hosts: all
  become: true
  vars:
    consul_gossip_keys:
      - +YpzB4/EoeaNcgtU9x1QtLAsQYlgRwVRw8qr50/tMds=
  roles:
    - role: "{{ lookup('ansible.builtin.env', 'MOLECULE_PROJECT_DIRECTORY') }}"
