---
- name: Converge
  hosts: all
  become: true
  vars:
    hashicorp_release_product: consul
    hashicorp_release_version: 1.20.1
  roles:
    - role: "{{ lookup('ansible.builtin.env', 'MOLECULE_PROJECT_DIRECTORY') }}"
