---
collections:
  - name: community.crypto
    version: ">=2.15.0"
  - name: community.general
    version: ">=10.5.0"
  - name: ansible.posix
    version: ">=1.5.0"
  - name: eugene_panin.base
    version: ">=0.3.0"
