---
dependency:
  name: galaxy
  options:
    requirements-file: molecule/guard/requirements.yml
driver:
  name: docker
platforms:
  - name: instance-vault-guard
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2404}-ansible:latest"
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_result_format: yaml
  inventory:
    group_vars:
      all:
        vault_bind_address: "{{ ansible_facts['default_ipv4']['address'] }}"
        vault_pki_dir: "{{ lookup('ansible.builtin.env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/pki"
        vault_init_output_path: "{{ lookup('ansible.builtin.env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/vault/init.json"
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
    verify: verify.yml
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - verify
    - destroy
