---
galaxy_info:
  role_name: consul
  namespace: eugene_panin
  author: Evgenii Panin
  description: Consul agent with gossip encryption, TLS and ACLs
  license: MIT
  min_ansible_version: "2.19"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
    - name: Debian
      versions:
        - bookworm
  galaxy_tags:
    - consul
    - hashicorp
    - discovery
dependencies: []
